# Site settings
title: April 1 arXiv
description: A collection of April Fools Day arXiv papers
baseurl: ""
url: "https://april1arxiv.github.io" 

# User settings
username: april1arxiv
email: april1arxiv@outlook.com
twitter_username: april1arxiv
github_username:  april1arxiv

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About
    url: /about

# Google services
google_analytics: G-T9BN62YQ4G

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
